# Nginx Reverse Proxy Service
# Handles SSL termination and routing for all services

services:
  nginx:
    image: nginx:alpine
    container_name: co-nginx-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PRIMARY_DOMAIN=${PRIMARY_DOMAIN}
      - MACHINE_ID=${MACHINE_ID}
      - WEBUI_DOMAIN=${WEBUI_DOMAIN}
      - PERPLEXICA_DOMAIN=${PERPLEXICA_DOMAIN}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - HOMEPAGE_DOMAIN=${HOMEPAGE_DOMAIN}
      - CANARY_DOMAIN=${CANARY_DOMAIN}
      - GENERIC_WEBUI_DOMAIN=${GENERIC_WEBUI_DOMAIN}
      - GENERIC_PERPLEXICA_DOMAIN=${GENERIC_PERPLEXICA_DOMAIN}
      - GENERIC_AUTH_DOMAIN=${GENERIC_AUTH_DOMAIN}
      - GENERIC_HOMEPAGE_DOMAIN=${GENERIC_HOMEPAGE_DOMAIN}
      - GLANCE_DOMAIN=${GLANCE_DOMAIN}
      - GENERIC_GLANCE_DOMAIN=${GENERIC_GLANCE_DOMAIN}
    volumes:
      - ./configs/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl/custom:ro
    depends_on:
      - open-webui
      - perplexica
      - searxng
      - homepage
      - glance
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    name: ${COMPOSE_PROJECT_NAME}_app-network