use_default_settings: true

general:
  instance_name: "SearxNG"

server:
  secret_key: "my-super-secret-searxng-key-for-perplexica-2025"
  limiter: false
  public_instance: false

search:
  safe_search: 0
  formats:
    - html
    - json

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Information'
  - 'Tracker URL remover'
  - 'Unit converter plugin'
