---
# Services Configuration for v0.9.10

# AI Platform Services
- AI Platform:
    - Open-WebUI Production:
        href: https://webui.yourdomain.com
        description: Main AI chat interface
        icon: si-openai
        
    - Open-WebUI Canary:
        href: https://webui-canary.yourdomain.com
        description: Testing environment
        icon: si-openai
        
    - Perplexica Search:
        href: https://perplexica.yourdomain.com
        description: AI-powered search
        icon: si-perplexity