---
# Homepage Configuration for v0.9.10 - Carian Observatory
title: Carian Observatory Platform

# Theme/appearance - simplified configuration
theme: dark
headerStyle: clean

# Layout
layout:
  AI Platform:
    style: row
    columns: 4

# Disable features that might cause issues
disableCollapse: false
showStats: true
target: _blank

# Language
language: en